#include "GLExt.hpp"

namespace Galatea
{
	namespace Display
	{
		GLExt::GLExt()
		{
			#define WGL_GETPROC(type, name) name = (type)(wglGetProcAddress(#name))

			//Initialization
			WGL_GETPROC(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
			WGL_GETPROC(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB);

			//Vertex Buffers
			WGL_GETPROC(PFNGLGENBUFFERSPROC, glGenBuffers);
			WGL_GETPROC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
			WGL_GETPROC(PFNGLBINDBUFFERPROC, glBindBuffer);
			WGL_GETPROC(PFNGLBUFFERDATAPROC, glBufferData);
			WGL_GETPROC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
			WGL_GETPROC(PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray);
			WGL_GETPROC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);

			//Shaders
			WGL_GETPROC(PFNGLCREATESHADERPROC, glCreateShader);
			WGL_GETPROC(PFNGLDELETESHADERPROC, glDeleteShader);
			WGL_GETPROC(PFNGLSHADERSOURCEPROC, glShaderSource);
			WGL_GETPROC(PFNGLCOMPILESHADERPROC, glCompileShader);
			WGL_GETPROC(PFNGLGETSHADERIVPROC, glGetShaderiv);
			WGL_GETPROC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
			WGL_GETPROC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
			WGL_GETPROC(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
			WGL_GETPROC(PFNGLATTACHSHADERPROC, glAttachShader);
			WGL_GETPROC(PFNGLDETACHSHADERPROC, glDetachShader);
			WGL_GETPROC(PFNGLLINKPROGRAMPROC, glLinkProgram);
			WGL_GETPROC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
			WGL_GETPROC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
			WGL_GETPROC(PFNGLUSEPROGRAMPROC, glUseProgram);
			WGL_GETPROC(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv);
			WGL_GETPROC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
		}

		GLExt::~GLExt() {}
	}
}
